version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - eqrx
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - eqrx
