linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - errname
    - exhaustive
    - forbidigo
    - goconst
    - godox
    - promlinter
    - tagliatelle
    - wsl
    # - exhaustivestruct # Not for general usage.
    # - golint # Deprecated.
    # - interfacer # Deprecated.
    # - maligned # Deprecated.
    # - scopelint # Deprecated.
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  include:
    - EXC0001 # Do not ignore errors.
    - EXC0002 # Actually require docs for exports.
    - EXC0003 # Don't name packages "test".
    - EXC0004 # Unsafe pointer is worth a "nolint".
    - EXC0005 # No ineffective breaks.
    - EXC0006 # Unsafe pointer is worth a "nolint".
    - EXC0009 # File permissions are important.
    - EXC0011 # Comment style checks.
    - EXC0012 # Actually require docs for exports.
    - EXC0013 # Actually require docs for exports.
    - EXC0014 # Actually require docs for exports.
    - EXC0015 # Actually require docs for exports.
