name: Go
on: [push]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with: { version: v1.44.0 }
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with: { go-version: 1.17 }
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/checkout@v2
      - run: ./build.sh
